INSERT INTO products (name, description)
VALUES
('Pão de Forma Integral', 'Pão integral com grãos, saudável e nutritivo.'),
('Biscoito de Chocolate', 'Biscoito crocante de chocolate, perfeito para lanches.'),
('Baguete', 'Pão longo e crocante, ideal para fazer sanduíches.'),
('Bolo de Chocolate', 'Bolo úmido e saboroso de chocolate.'),
('Torta de Frutas', 'Torta doce recheada com variedade de frutas frescas.'),
('Croissant de Queijo', 'Massa folhada e crocante recheada com queijo.'),
('Pão de Milho', 'Pão feito com farinha de milho, típico e saboroso.'),
('Bolinho de Bacalhau', 'Bolinho frito feito com bacalhau e temperos.'),
('Rosquinha de Leite', 'Rosquinha doce e macia com cobertura de leite condensado.'),
('Sonho', 'Pão doce recheado com creme de confeiteiro e coberto com açúcar.'),
('Empada de Frango', 'Massa folhada recheada com frango desfiado e temperos.'),
('Bolo de Cenoura', 'Bolo fofinho de cenoura coberto com glacê de chocolate.'),
('Pão de Queijo', 'Pãozinho de queijo quente e delicioso.'),
('Pão Integral com Castanhas', 'Pão integral com castanhas, rico em fibras e nutrientes.'),
('Torta de Limão', 'Torta doce com recheio de creme de limão e cobertura de merengue.'),
('Pão de Abóbora', 'Pão feito com purê de abóbora, macio e saboroso.'),
('Biscoito de Gengibre', 'Biscoito de gengibre decorado, perfeito para o Natal.'),
('Pão Sírio', 'Pão fino e macio, ótimo para sanduíches e wraps.'),
('Bolo de Amêndoas', 'Bolo com massa de amêndoas e cobertura de açúcar.'),
('Carolina', 'Massa leve recheada com creme e coberta com açúcar de confeiteiro.'),
('Pão de Alho', 'Pãozinho temperado com alho e ervas, ideal para churrascos.'),
('Bolinho de Chuva', 'Bolinho frito e açucarado, perfeito para acompanhar o café.'),
('Pão Australiano', 'Pão escuro e adocicado, feito com mel e cacau.'),
('Torta de Frango com Catupiry', 'Torta salgada recheada com frango e queijo Catupiry.'),
('Rosca Doce', 'Rosca doce e macia com cobertura de açúcar e canela.');
